//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ciudades
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ciudades()
    {
        this.usuarios = new HashSet<usuarios>();
    }

    public int id_ciudad { get; set; }
    public string nombre { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<usuarios> usuarios { get; set; }
}

public partial class imagenes
{
    public int id { get; set; }
    public string src { get; set; }
    public int id_usuario { get; set; }

    public virtual usuarios usuarios { get; set; }
}

public partial class usuarios
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public usuarios()
    {
        this.imagenes = new HashSet<imagenes>();
    }

    public int id_usuario { get; set; }
    public string correo { get; set; }
    public string pass { get; set; }
    public Nullable<bool> sexo { get; set; }
    public double altura { get; set; }
    public Nullable<double> peso { get; set; }
    public Nullable<int> grupo_etnico { get; set; }
    public Nullable<System.DateTime> fecha_nacimiento { get; set; }
    public string nombre { get; set; }
    public string apellidos { get; set; }
    public string nick { get; set; }
    public string telefono { get; set; }
    public Nullable<int> tipo_trabajo { get; set; }
    public int id_ciudad { get; set; }

    public virtual ciudades ciudades { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<imagenes> imagenes { get; set; }
}
